# Generated by Django 4.1.2 on 2022-10-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
