# Generated by Django 4.1.2 on 2022-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='facility_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
