# Generated by Django 4.1.2 on 2022-10-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_administrator_facility_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.administrator')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('website_url', models.CharField(max_length=150, verbose_name='Website URL')),
                ('taxID', models.CharField(max_length=50, verbose_name='Tax ID Number')),
            ],
        ),
    ]
