# Generated by Django 4.1.2 on 2022-10-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('ssn', models.CharField(max_length=50, verbose_name='SSN')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('specialty', models.TextField(max_length=50, verbose_name='Specialty')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                
            ],
        ),
    ]
