# Generated by Django 4.1.2 on 2022-10-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='has_been_disqualified',
            field=models.BooleanField(default=False, verbose_name='Have you ever been placed on the disqualified employees Registry?'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='has_been_terminated',
            field=models.BooleanField(default=False, verbose_name="Have you ever had you're employment terminated?"),
        ),
    ]
