# Generated by Django 4.1.2 on 2022-10-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seeker_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerEmploymentVerifications',
            fields=[
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.seeker')),
                ('photo_URL', models.URLField(max_length=255, verbose_name='Photo URL')),
                ('resume_URL', models.URLField(max_length=255, verbose_name='Resume URL')),
                ('tb_verification_URL', models.URLField(max_length=255, verbose_name='TB Verification')),
                ('flu_verification_URL', models.URLField(max_length=255, verbose_name='Flu Verification')),
                ('covid_verification_URL', models.URLField(max_length=255, verbose_name='COVID 19 Verification')),
            ],
        ),
    ]
